#line 2 "sidstar.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_accept[483] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   71,   21,    5,    5,   21,   21,   21,   21,
       21,   21,   21,   70,   70,   70,   15,   15,   12,    9,
        9,   10,   13,   11,   14,   70,   70,   19,   70,   27,
       27,   27,   27,   27,   29,   28,   46,   69,   69,   69,

       69,   69,   49,   49,   49,   49,   49,   49,   49,   50,
       69,   69,   55,   62,   70,   70,   68,   70,   70,   67,
       69,   69,   61,   61,   61,   61,   61,   61,   69,   69,
       70,   70,   70,   70,   34,   47,   47,   47,   47,   47,
       70,   70,   70,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   15,   15,   10,   13,   11,   11,   14,
       14,    0,    0,   19,    0,   27,   27,   27,   27,   27,
       29,   28,    0,    0,    0,    0,    0,   49,   49,   49,
       49,   49,   49,   49,    0,   50,    0,    0,   55,   62,
        0,    0,   68,    0,    0,   67,    0,    0,   61,   61,

       61,   61,   61,   61,    0,    0,    0,    0,    0,    0,
       34,   47,   47,   47,   47,   47,   47,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    0,    0,    0,
        7,   15,   11,   14,    0,   18,   23,   27,   25,   23,
       27,   38,   41,   39,   40,    0,   38,   41,   49,   39,
       40,   49,   51,    0,    0,    0,    0,    0,    0,    0,
        0,   38,   41,   39,   40,   61,    0,    0,    0,    0,
       33,    0,   38,   41,   39,   40,   47,    0,    0,    0,
        0,    0,    0,    0,   17,   22,    0,    0,   15,    0,
       27,   27,    0,   49,   49,    0,    0,    0,    0,    0,

        0,    0,    0,   61,    0,    0,   31,    0,    0,   47,
        0,    0,    0,    0,    0,    6,    0,    3,    0,   30,
        0,   15,    0,   27,   27,    0,   49,    0,   54,    0,
       58,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,    0,    8,    0,   27,
       27,    0,    0,   49,    0,    0,    0,    0,    0,   65,
        0,   59,    0,    0,    0,    0,    0,    0,    0,    0,
       20,   24,   27,    0,    0,   48,    0,    0,    0,    0,
       64,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       16,   27,    0,    0,    0,    0,    0,    0,   66,   60,

       32,    0,   36,    0,   56,    0,    0,    4,   27,    0,
        0,    0,    0,    0,    0,    0,    0,   35,   26,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,   52,
       53,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   37,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   57,   63,    0,    0,    0,    0,
        0,    0,   42,    0,    0,   43,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   44,    0,
       45,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       17,   24,   25,   26,   27,   28,   29,   30,   31,   17,
        1,    1,    1,    1,    1,    1,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,    1,   33,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[34] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1
    } ;

static yyconst short int yy_base[507] =
    {   0,
        0,   24,    3,    5,   49,   82,  104,  126,  613,  612,
      611,  610,  609,  608,  607,  606,    7,    9,  159,  192,
      587,  586,  225,  258,  291,  324,  357,  390,  423,  456,
      489,    0,   15,   34,  603,  602,   40,   50,   53,   63,
       32,   67,  522,  555,    0,    0,   49,   50,  583,  582,
       78,   82,  588,  621,  654,  687,   53,   84,  598,  597,
      591,  590,  602,  774,  774,  774,  595,  577,  578,  582,
      589,  575,   18,  774,  574,  577,    0,  578,  774,  774,
      774,  578,  577,    0,    4,  562,  561,    0,  564,    0,
      557,  556,  560,  551,    0,    0,  774,  774,  558,  562,

      551,   19,    0,    0,  555,  558,  539,  545,   71,   66,
      539,  541,  556,  546,  531,  530,  543,  528,  535,  538,
       48,   87,    0,    0,  528,  532,  521,   73,   89,   95,
      515,  519,  518,  514,    0,    0,  520,  523,  512,   94,
      509,  510,  506,  484,  463,  474,  454,  457,  452,  468,
      470,  466,  446,    0,  449,  467,  466,  465,  105,  463,
      119,  457,  438,    0,  455,    0,  454,  435,  443,  445,
        0,    0,  422,  437,  421,  430,  422,    0,  415,  430,
      431,  413,  423,  416,  432,  123,  433,  423,  427,  426,
      406,  405,  415,  395,  410,  412,  396,  413,    0,  386,

      401,  385,  395,  388,  389,  406,  401,  397,  378,  398,
        0,    0,  375,  390,  374,  384,  377,  377,  388,  376,
      394,  774,  371,  375,  376,  375,  361,  360,  360,  370,
      774,  363,  374,  373,  355,  774,  774,  353,    0,    0,
      356,  774,  774,  774,  774,  355,    0,    0,  351,    0,
        0,  353,  366,  350,  359,  358,  353,  356,  341,  346,
      352,    0,    0,    0,    0,  343,  342,  343,  331,  329,
      774,  332,    0,    0,    0,    0,  331,  327,  342,  329,
      326,  339,  321,  117,  774,  774,  320,  328,  321,  321,
      325,  315,  335,  325,  333,  312,  324,  310,  314,  308,

      309,  325,  307,  318,  317,  304,  774,  293,  293,  313,
      294,  292,  310,  305,  286,  774,  308,  774,  307,  774,
      279,  287,  278,  295,  289,  108,  285,  299,  774,  292,
      774,  291,  276,  286,  268,  283,  260,  281,  272,  279,
      263,  272,  271,  268,  276,  774,  266,    0,  252,  251,
      249,  262,  257,  241,  126,  259,  257,  243,  251,  774,
      250,  774,  241,  237,  247,  232,  239,  239,  228,  227,
      774,    0,  232,  234,  232,    0,  236,  232,  220,  219,
      774,  211,  210,  214,  222,  221,  213,  204,  221,  229,
      774,  208,  198,  208,  200,  202,  194,  193,  774,  774,

      774,  196,  774,  209,  774,  191,  212,  774,  193,  209,
      186,  183,  188,  205,  204,  186,  196,  774,    0,  194,
      200,  191,  173,  177,  176,  774,  184,  175,  179,  774,
      774,  181,  180,  175,  162,  169,  173,  172,  157,  169,
      156,  163,  162,  774,  167,  164,  167,  166,  147,  162,
      152,  151,  165,  142,  774,  774,  154,  162,  142,  144,
      126,  138,  149,  122,  128,  145,  120,  124,  133,  116,
      119,  129,  127,  115,  117,  118,   92,   80,  774,   58,
      774,  774,  720,  723,  726,  729,  732,  735,  738,  741,
      744,  747,  750,   75,   32,  752,  754,  756,   26,   17,

      758,    7,  761,  764,  767,  770
    } ;

static yyconst short int yy_def[507] =
    {   0,
      483,  483,  484,  484,  485,  485,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  486,  486,
      484,  484,  487,  487,  488,  488,  489,  489,  490,  490,
      482,   31,   30,   30,   30,   30,  484,  484,  484,  484,
       30,   30,  491,  491,   30,   30,   30,   30,  484,  484,
      484,  484,  492,  492,  493,  493,  484,  484,  484,  484,
      484,  484,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  494,  494,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  495,  482,  496,
      496,  496,  496,  496,  497,  498,  482,  482,  482,  482,

      482,  482,  499,  499,  499,  499,  499,  499,  499,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  500,  500,  500,  500,  500,  500,  482,  482,
      482,  482,  482,  482,  501,  502,  502,  502,  502,  502,
      482,  482,  482,  503,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  494,  494,  482,  482,  482,  482,  482,
      482,  482,  482,  495,  482,  496,  496,  496,  496,  496,
      497,  498,  482,  482,  482,  482,  482,  499,  499,  499,
      499,  499,  499,  499,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  500,  500,

      500,  500,  500,  500,  482,  482,  482,  482,  482,  482,
      501,  502,  502,  502,  502,  502,  502,  482,  482,  482,
      503,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  494,  482,  482,  482,  482,  482,  496,  496,  496,
      496,  482,  482,  482,  482,  482,  499,  499,  499,  499,
      499,  499,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  500,  500,  500,  500,  500,  482,  482,  482,  482,
      482,  482,  502,  502,  502,  502,  502,  482,  482,  482,
      482,  482,  482,  504,  482,  482,  482,  482,  494,  482,
      496,  496,  482,  499,  499,  482,  482,  482,  482,  482,

      482,  482,  482,  500,  482,  482,  482,  482,  482,  502,
      482,  482,  482,  482,  482,  482,  504,  482,  505,  482,
      482,  494,  482,  496,  496,  482,  499,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  505,  482,  482,  494,  482,  496,
      496,  482,  482,  499,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  496,  496,  482,  482,  499,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  506,
      482,  496,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  506,  482,  496,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  496,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,    0,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482
    } ;

static yyconst short int yy_nxt[808] =
    {   0,
      482,   65,   66,   65,  158,   67,  159,   68,  160,  212,
      161,   69,   70,   71,   75,   76,   75,   76,   86,  199,
       86,  110,  111,   72,   73,   65,   66,   65,  178,   67,
       87,   68,   87,  150,  164,   69,   70,   71,  120,  112,
      110,  111,  176,  151,  121,  177,  114,   72,   73,   74,
       74,   74,   74,   74,   74,  115,  114,  122,  112,  117,
      141,  129,  129,  173,  142,  115,  116,   78,  118,  117,
      185,  197,  186,  120,  130,  130,  116,  154,  118,  121,
      119,   74,   74,   74,   74,   74,   74,   74,  481,  132,
      119,  141,  122,  132,  183,  142,  203,  184,  480,  204,

       78,  133,  131,  134,  173,  133,  131,  134,  198,  158,
      176,  159,  205,  177,   74,   79,  206,  216,  176,  318,
      217,  177,  479,  160,   80,  161,  352,  185,   80,  186,
      478,  353,   79,  377,  378,  477,   81,   79,  476,  475,
      474,  319,  473,  472,  471,  470,   80,  469,  468,  467,
       80,  466,  465,  464,   79,  463,  462,  461,   81,   74,
       74,   74,   74,   74,   74,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,   74,   74,   74,   74,   74,   74,   74,  434,  433,

      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  408,  418,  417,  416,  415,  414,
      413,  412,  411,  410,   74,   74,   74,   74,   74,  409,
       74,  408,  406,  405,  404,  403,   91,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,   92,   93,
       94,  391,  390,  389,  388,  387,  386,   74,   74,   74,
       74,   74,  385,   74,  384,  383,  382,  381,  380,   91,
      379,  376,  375,  374,  373,  372,  371,  370,  346,  369,
      368,   92,   93,   94,  367,  366,  365,  364,  363,  362,
       74,   74,   74,   74,   74,  361,   74,  360,  359,  358,

      357,  356,  355,  354,  351,  350,  349,  348,  347,  346,
      318,  344,  343,  342,  341,  340,  326,  339,  338,  337,
      336,  326,  335,   74,   74,   74,   74,   74,  334,   74,
      333,  332,  331,  330,  329,  328,  326,  327,  326,  325,
      324,  323,  322,  321,  320,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,   74,   74,   74,   74,
       74,  305,   74,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  253,  295,  294,  293,  292,  291,  290,  234,
      233,  289,  288,  287,  286,  285,  284,  283,  282,   74,
       74,   74,   74,   74,  281,   74,  222,  280,  279,  278,

      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  196,  259,
      258,  193,   74,   74,   74,   97,   74,   74,   74,   74,
      257,  256,  190,  189,  255,   99,  254,  100,  253,  252,
      251,  250,  249,  248,  247,  246,  101,  245,  102,  244,
      243,  242,  241,  240,   74,   74,   74,   74,   97,   74,
       74,   74,   74,  239,  238,  237,  236,  235,   99,  234,
      100,  233,  157,  156,  232,  231,  230,  229,  228,  101,
      227,  102,  226,  225,  224,  223,  222,   74,   74,   74,
       74,   97,   74,   74,   74,  103,  104,  104,  104,  104,

      104,  105,  104,  106,  104,  104,  104,  104,  104,  104,
      107,  104,  108,  104,  109,  104,  104,  104,  104,  104,
      103,   74,   74,   74,   97,   74,   74,   74,  123,  220,
      219,  218,  215,  214,  125,  213,  126,  210,  209,  208,
      207,  202,  201,  200,  196,  127,  195,  128,  194,  193,
      192,  191,  190,  123,   74,   74,   74,   97,   74,   74,
       74,  123,  189,  188,  187,  182,  181,  125,  180,  126,
      179,  175,  174,  173,  170,  169,  168,  167,  127,  165,
      128,  163,  162,  157,  156,  155,  123,   74,   74,   74,
       74,   74,  153,   74,  152,  149,  148,  147,  146,  145,

      144,  482,  143,  143,  141,  141,  131,  131,  113,  113,
       89,   89,   85,   85,   84,   84,   83,   83,   82,   82,
       74,   74,   74,   74,   74,  482,   74,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,   74,   74,   74,   97,   74,   74,   74,
      482,  482,  482,  482,  482,  482,  137,  482,  138,  482,
      482,  482,  482,  482,  482,  482,  482,  139,  482,  140,
      482,  482,  482,  482,  482,  482,   74,   74,   74,   97,
       74,   74,   74,  482,  482,  482,  482,  482,  482,  137,

      482,  138,  482,  482,  482,  482,  482,  482,  482,  482,
      139,  482,  140,  482,  482,  482,  482,  482,  482,   74,
       64,   64,   64,   74,   74,   74,   77,   77,   77,   88,
       88,   88,   90,   90,   90,   95,   95,   95,   96,   96,
       96,   98,   98,   98,  124,  124,  124,  135,  135,  135,
      136,  136,  136,  166,  166,  171,  171,  172,  172,  211,
      211,  221,  221,  221,  317,  317,  317,  345,  345,  345,
      407,  407,  407,   63,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482
    } ;

static yyconst short int yy_chk[808] =
    {   0,
        0,    1,    1,    1,   84,    1,   84,    1,   85,  502,
       85,    1,    1,    1,    3,    3,    4,    4,   17,  500,
       18,   33,   33,    1,    1,    2,    2,    2,  499,    2,
       17,    2,   18,   73,  495,    2,    2,    2,   41,   33,
       34,   34,  102,   73,   41,  102,   37,    2,    2,    5,
        5,    5,    5,    5,    5,   37,   38,   41,   34,   39,
       57,   47,   48,  121,   57,   38,   37,    5,   39,   40,
      110,  121,  110,   42,   47,   48,   38,  494,   40,   42,
       39,    5,    6,    6,    6,    6,    6,    6,  480,   51,
       40,   58,   42,   52,  109,   58,  128,  109,  478,  128,

        6,   51,   51,   51,  129,   52,   52,   52,  122,  159,
      122,  159,  129,  122,    6,    7,  130,  140,  130,  284,
      140,  130,  477,  161,    7,  161,  326,  186,    7,  186,
      476,  326,    7,  355,  355,  475,    7,    8,  474,  473,
      472,  284,  471,  470,  469,  468,    8,  467,  466,  465,
        8,  464,  463,  462,    8,  461,  460,  459,    8,   19,
       19,   19,   19,   19,   19,  458,  457,  454,  453,  452,
      451,  450,  449,  448,  447,  446,  445,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  429,
      428,   19,   20,   20,   20,   20,   20,   20,  427,  425,

      424,  423,  422,  421,  420,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  407,  406,  404,  402,  398,  397,
      396,  395,  394,  393,   20,   23,   23,   23,   23,  392,
       23,  390,  389,  388,  387,  386,   23,  385,  384,  383,
      382,  380,  379,  378,  377,  375,  374,  373,   23,   23,
       23,  370,  369,  368,  367,  366,  365,   23,   24,   24,
       24,   24,  364,   24,  363,  361,  359,  358,  357,   24,
      356,  354,  353,  352,  351,  350,  349,  347,  345,  344,
      343,   24,   24,   24,  342,  341,  340,  339,  338,  337,
       24,   25,   25,   25,   25,  336,   25,  335,  334,  333,

      332,  330,  328,  327,  325,  324,  323,  322,  321,  319,
      317,  315,  314,  313,  312,  311,  310,  309,  308,  306,
      305,  304,  303,   25,   26,   26,   26,   26,  302,   26,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  283,  282,  281,  280,  279,
      278,  277,  272,  270,  269,  268,   26,   27,   27,   27,
       27,  267,   27,  266,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  249,  246,  241,  238,  235,  234,
      233,  232,  230,  229,  228,  227,  226,  225,  224,   27,
       28,   28,   28,   28,  223,   28,  221,  220,  219,  218,

      217,  216,  215,  214,  213,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  198,  197,  196,  195,
      194,  193,   28,   29,   29,   29,   29,   29,   29,   29,
      192,  191,  190,  189,  188,   29,  187,   29,  185,  184,
      183,  182,  181,  180,  179,  177,   29,  176,   29,  175,
      174,  173,  170,  169,   29,   29,   30,   30,   30,   30,
       30,   30,   30,  168,  167,  165,  163,  162,   30,  160,
       30,  158,  157,  156,  155,  153,  152,  151,  150,   30,
      149,   30,  148,  147,  146,  145,  144,   30,   30,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   43,   43,   43,   43,   43,   43,   43,  143,
      142,  141,  139,  138,   43,  137,   43,  134,  133,  132,
      131,  127,  126,  125,  120,   43,  119,   43,  118,  117,
      116,  115,  114,   43,   43,   44,   44,   44,   44,   44,
       44,   44,  113,  112,  111,  108,  107,   44,  106,   44,
      105,  101,  100,   99,   94,   93,   92,   91,   44,   89,
       44,   87,   86,   83,   82,   78,   44,   44,   53,   53,
       53,   53,   76,   53,   75,   72,   71,   70,   69,   68,

       67,   63,   62,   61,   60,   59,   50,   49,   36,   35,
       22,   21,   16,   15,   14,   13,   12,   11,   10,    9,
       53,   54,   54,   54,   54,    0,   54,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   54,   55,   55,   55,   55,   55,   55,
        0,    0,    0,    0,    0,    0,   55,    0,   55,    0,
        0,    0,    0,    0,    0,    0,    0,   55,    0,   55,
        0,    0,    0,    0,    0,    0,   55,   56,   56,   56,
       56,   56,   56,    0,    0,    0,    0,    0,    0,   56,

        0,   56,    0,    0,    0,    0,    0,    0,    0,    0,
       56,    0,   56,    0,    0,    0,    0,    0,    0,   56,
      483,  483,  483,  484,  484,  484,  485,  485,  485,  486,
      486,  486,  487,  487,  487,  488,  488,  488,  489,  489,
      489,  490,  490,  490,  491,  491,  491,  492,  492,  492,
      493,  493,  493,  496,  496,  497,  497,  498,  498,  501,
      501,  503,  503,  503,  504,  504,  504,  505,  505,  505,
      506,  506,  506,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sidstar.l"
#define INITIAL 0
#line 4 "sidstar.l"
#include <sidstar.h>
#include <stdio.h>
//#include "RobotTokens.h"
#include <math.h>



// Flex использует макрос YY_DECL как основу объявления функции, сканирующей следующий токен.
// По умолчанию значение макроса YY_DECL равно `int yylex()`
// Но мы назовём функцию ScanToken.
#define YY_DECL int ScanToken()
#define fileno _fileno
#define isatty _isatty
int sign;
float lat, lon;



#define fixes 1
#define fix 2
#define latlon 3
#define ns 4
#define ew 5
#define degreeslat 6
#define degreeslon 7

#define rnws 8
#define rnw 9

#define sids 10
#define sid 11
#define sidtrans 12
#define sidrun 13

#define croute 14
#define fixroute 15
#define routealt 16
#define fixspeed 17
#define trkroute 18
#define hdgroute 19
#define routeradial 20
#define routeradialfix 21
#define routeuntil 22
#define trkrouteradial 23
#define stars 24
#define star 25
#define starrnw 26
#define rnwroute 27
#define approach 28
#define approaches 29
#define trkuntilfrom 30

#line 761 "sidstar.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "sidstar.l"


#line 915 "sidstar.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 483 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 774 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "sidstar.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "sidstar.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "sidstar.l"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "sidstar.l"

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "sidstar.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "sidstar.l"
{sidstar.efixes = new std::vector<sfix>(); BEGIN(fixes);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "sidstar.l"
{BEGIN(fix);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "sidstar.l"
{BEGIN(latlon);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "sidstar.l"
{if (yytext == "N") {sign = 0;} else {sign = 1;}; BEGIN(ns);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "sidstar.l"
{lat = atof(yytext);BEGIN(degreeslat);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "sidstar.l"
{float t; t = atof(yytext); lat = lat + t/60.0; if(!sign){lat=-lat;}; pfix.lat = lat; BEGIN(latlon);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "sidstar.l"
{if (yytext == "E") {sign = 0;} else {sign = 1;}; BEGIN(ew);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "sidstar.l"
{lon = atof(yytext);BEGIN(degreeslon);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "sidstar.l"
{float t; t = atof(yytext); lon = lon + t/60.0; if(!sign){lon=-lon;}; pfix.lon = lon; printf(" lat: %f, lon: %f\n",lat,lon); sidstar.efixes->push_back(pfix); BEGIN(fixes);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 44 "sidstar.l"
{pfix.name = std::string(yytext); printf("Fix point: %s with ",yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 45 "sidstar.l"
{BEGIN(0);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "sidstar.l"
{printf("Used runways: "); BEGIN(rnws);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "sidstar.l"
{BEGIN(rnw);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "sidstar.l"
{printf("%s, ", yytext); BEGIN(rnws);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "sidstar.l"
{BEGIN(0); printf("\b\b\n");};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "sidstar.l"
{printf("\nWith out FIX %s\n",yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "sidstar.l"
{mode = ESIDS; sidstar.esids = new std::vector<ssid>(); printf("SIDs: "); BEGIN(sids);psid = {"", NULL, NULL, NULL};}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "sidstar.l"
{if(psid.name != "") {sidstar.esids->push_back(psid);}; psid = {"", NULL, NULL, NULL}; BEGIN(sid);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "sidstar.l"
{PointVector->push_back(prnwsid); prnwsid = {"", NULL}; sidstar.esids->push_back(psid); printf("END"); BEGIN(0);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "sidstar.l"
{
		if (PointVector != NULL)
		{
			//PointVector->push_back(prnwsid); 
		}
		if(psid.ernws == NULL)
		{
			psid.ernws = new std::vector<srnwsid>();
		}; 
		PointVector = psid.ernws; 
		printf("for runway "); 
		BEGIN(sidrun);
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "sidstar.l"
{if (PointVector != NULL){/*PointVector->push_back(prnwsid);*/}; if(psid.etrans == NULL){psid.etrans = new std::vector<srnwsid>();}; PointVector = psid.etrans; printf("with transition "); BEGIN(sidtrans);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "sidstar.l"
{psid.name = std::string(yytext); printf("SID: %s ", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "sidstar.l"
{prnwsid.name = std::string(yytext); stemp = prnwsid.name; prnwsid.eroute = new std::vector<sroute>(); proute = {0}; printf("%s", yytext); BEGIN(croute); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "sidstar.l"
{prnwsid.name = std::string(yytext); prnwsid.eroute = new std::vector<sroute>(); proute = {0}; printf("%s", yytext); BEGIN(croute); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "sidstar.l"
{mode = ESTARS; sidstar.estars = new std::vector<ssid>(); printf("STARSs: "); BEGIN(stars);psid = {"", NULL, NULL, NULL};}	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "sidstar.l"
{if(psid.name != "") {sidstar.estars->push_back(psid);}; psid = {"", NULL, NULL, NULL};
		if(psid.ernws == NULL)
		{
			psid.ernws = new std::vector<srnwsid>();
		}; 
		PointVector = psid.ernws; 
		printf("for runway "); 
		BEGIN(sidrun);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "sidstar.l"
{PointVector->push_back(prnwsid); prnwsid = {"", NULL}; sidstar.estars->push_back(psid); printf("END"); BEGIN(0);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "sidstar.l"
{ if (psid.ernw == NULL){psid.ernw = new std::vector<std::string>();}; BEGIN(starrnw); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "sidstar.l"
{psid.ernw->push_back(std::string(yytext)); BEGIN(star);};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "sidstar.l"
{mode = EAPPROACHES; sidstar.eapproaches = new std::vector<ssid>(); printf("APPROACHes: "); BEGIN(approaches);psid = {"", NULL, NULL, NULL};}	
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "sidstar.l"
{if(psid.name != "") {sidstar.eapproaches->push_back(psid);}; psid = {"", NULL, NULL, NULL};
		if(psid.ernws == NULL)
		{
			psid.ernws = new std::vector<srnwsid>();
		}; 
		PointVector = psid.ernws; 
		printf("for runway "); 
		BEGIN(sidrun);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "sidstar.l"
{PointVector->push_back(prnwsid); prnwsid = {"", NULL}; sidstar.eapproaches->push_back(psid); printf("END"); BEGIN(0);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = FIX; BEGIN(fixroute);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = RNW; BEGIN(rnwroute);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; BEGIN(trkroute);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; BEGIN(hdgroute);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = TURNLEFT; BEGIN(fixroute);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = TURNRIGHT; BEGIN(fixroute);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = TURNLEFTOVERFLY; BEGIN(fixroute);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "sidstar.l"
{if(proute.type != NONE) {prnwsid.eroute->push_back(proute);};proute = {0}; proute.type = TURNRIGHTOVERFLY; BEGIN(fixroute);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "sidstar.l"
{
	if(proute.type != NONE) 
	{
		prnwsid.eroute->push_back(proute);
	};
	PointVector->push_back(prnwsid);
	prnwsid = {"", NULL}; 
	proute = {0}; 
	if (mode == ESIDS)
	{
		BEGIN(sid);
	}
	if (mode == ESTARS)
	{
		psid.name = stemp;
		BEGIN(star);
	}
	if (mode == EAPPROACHES)
	{
		psid.name = stemp;
		BEGIN(approach);
	}
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "sidstar.l"
{proute.name = std::string(yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 133 "sidstar.l"
{proute.type = FIXOVERFY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 134 "sidstar.l"
{proute.name = std::string(yytext); BEGIN(routealt);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "sidstar.l"
{
	if (proute.alt != 0)
	{
		float t = atoi(yytext);
		if (t < proute.alt)
		{
			proute.alt2 = proute.alt;
			proute.alt = t;
		}
		else
		{
			proute.alt2 = t;
		};
	}
	else
	{
		proute.alt = atoi(yytext); 
	};
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 154 "sidstar.l"
{proute.dist = atof(yytext); BEGIN(trkuntilfrom);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 155 "sidstar.l"
{
	if (proute.alttype == ATORBELOW)
	{
		proute.alttype = ABOVEBELOW;
	}
	else
	{
		proute.alttype = ATORABOVE;
	}
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 165 "sidstar.l"
{
	if (proute.alttype == ATORABOVE)
	{
		proute.alttype = ABOVEBELOW;
	}
	else
	{
		proute.alttype = ATORBELOW;
	}
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 175 "sidstar.l"
{BEGIN(fixspeed); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 176 "sidstar.l"
{proute.speed = atoi(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 178 "sidstar.l"
{proute.type = TRKUNTILFROMFIX;BEGIN(routeradialfix);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 180 "sidstar.l"
{ BEGIN(routeradial);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 181 "sidstar.l"
{proute.type = TRKUNTIL; BEGIN(routealt); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 182 "sidstar.l"
{proute.type = TRKINTERCEPTTOFIX;BEGIN(routeradialfix);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 183 "sidstar.l"
{proute.type = TRKINTERCEPTFROMFIX;BEGIN(routeradialfix);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 184 "sidstar.l"
{proute.name = std::string(yytext); BEGIN(routealt);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 185 "sidstar.l"
{proute.trk = atoi(yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 187 "sidstar.l"
{ BEGIN(routeradial);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 188 "sidstar.l"
{proute.type = HDGVECTORS; BEGIN(routealt);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 189 "sidstar.l"
{proute.type = HDGINTERCEPTTOFIX;BEGIN(routeradialfix);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 190 "sidstar.l"
{proute.type = HDGINTERCEPTFROMFIX;BEGIN(routeradialfix);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 191 "sidstar.l"
{proute.radial = atoi(yytext);}; 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 192 "sidstar.l"
{proute.hdg = atoi(yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 193 "sidstar.l"
{MessageBox(0,L"ERR",LPWSTR(yytext),MB_OK);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(fixes):
case YY_STATE_EOF(fix):
case YY_STATE_EOF(latlon):
case YY_STATE_EOF(ns):
case YY_STATE_EOF(ew):
case YY_STATE_EOF(degreeslat):
case YY_STATE_EOF(degreeslon):
case YY_STATE_EOF(rnws):
case YY_STATE_EOF(rnw):
case YY_STATE_EOF(sids):
case YY_STATE_EOF(sid):
case YY_STATE_EOF(sidtrans):
case YY_STATE_EOF(sidrun):
case YY_STATE_EOF(croute):
case YY_STATE_EOF(fixroute):
case YY_STATE_EOF(routealt):
case YY_STATE_EOF(fixspeed):
case YY_STATE_EOF(trkroute):
case YY_STATE_EOF(hdgroute):
case YY_STATE_EOF(routeradial):
case YY_STATE_EOF(routeradialfix):
case YY_STATE_EOF(routeuntil):
case YY_STATE_EOF(trkrouteradial):
case YY_STATE_EOF(stars):
case YY_STATE_EOF(star):
case YY_STATE_EOF(starrnw):
case YY_STATE_EOF(rnwroute):
case YY_STATE_EOF(approach):
case YY_STATE_EOF(approaches):
case YY_STATE_EOF(trkuntilfrom):
#line 195 "sidstar.l"
{return 0;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 197 "sidstar.l"
ECHO;
	YY_BREAK
#line 1466 "sidstar.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 483 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 483 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 482);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 197 "sidstar.l"
