# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = MSFS2020_AutoFlight
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lSimConnect
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
QT= core gui [network]
include(MSFS2020_AutoFlight.pri)
