
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */

/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
 /* %ok-for-header */

 /* %if-reentrant */
 /* %endif */

 /* %if-not-reentrant */

 /* %endif */

 /* Enter a start condition.  This macro really ought to take a parameter,
  * but we do it the disgusting crufty way forced on us by the ()-less
  * definition of BEGIN.
  */
long yy_prev = 1;
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
 /* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE* yyin, * yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
  /* %if-c-only */
  FILE* yy_input_file;
  /* %endif */

  /* %if-c++-only */
  /* %endif */

  char* yy_ch_buf;		/* input buffer */
  char* yy_buf_pos;		/* current position in input buffer */

  /* Size of input buffer in bytes, not including room for EOB
   * characters.
   */
  int yy_buf_size;

  /* Number of characters read into yy_ch_buf, not including EOB
   * characters.
   */
  int yy_n_chars;

  /* Whether we "own" the buffer - i.e., we know we created it,
   * and can realloc() it to grow it, and should free() it to
   * delete it.
   */
  int yy_is_our_buffer;

  /* Whether this is an "interactive" input source; if so, and
   * if we're using stdio for input, then we want to use getc()
   * instead of fread(), to make sure we stop fetching input after
   * each newline.
   */
  int yy_is_interactive;

  /* Whether we're considered to be at the beginning of a line.
   * If so, '^' rules will be active on the next match, otherwise
   * not.
   */
  int yy_at_bol;

  int yy_bs_lineno; /**< The line count. */
  int yy_bs_column; /**< The column count. */

/* Whether to try to fill the input buffer when we reach the
 * end of it.
 */
  int yy_fill_buffer;

  int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
  /* When an EOF's been seen but there's still some text to process
   * then we mark the buffer as YY_EOF_PENDING, to indicate that we
   * shouldn't try reading from the input source any more.  We might
   * still have a bunch of tokens to match, though, because of
   * possible backing-up.
   *
   * When we actually see the EOF, we change the status to "new"
   * (via yyrestart()), so that the user can continue scanning by
   * just pointing yyin at a new input file.
   */
#define YY_BUFFER_EOF_PENDING 2

};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE* yy_buffer_stack = NULL; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
 /* Same as previous macro, but useful when we know that the buffer stack is not
  * NULL or when we need an lvalue. For internal use only.
  */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

  /* %if-c-only Standard (non-C++) definition */

  /* %if-not-reentrant */
  /* %not-for-header */
  /* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char* yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart(FILE* input_file);
void yy_switch_to_buffer(YY_BUFFER_STATE new_buffer);
YY_BUFFER_STATE yy_create_buffer(FILE* file, int size);
void yy_delete_buffer(YY_BUFFER_STATE b);
void yy_flush_buffer(YY_BUFFER_STATE b);
void yypush_buffer_state(YY_BUFFER_STATE new_buffer);
void yypop_buffer_state(void);

static void yyensure_buffer_stack(void);
static void yy_load_buffer_state(void);
static void yy_init_buffer(YY_BUFFER_STATE b, FILE* file);
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t size);
YY_BUFFER_STATE yy_scan_string(const char* yy_str);
YY_BUFFER_STATE yy_scan_bytes(const char* bytes, int len);

/* %endif */

void* yyalloc(yy_size_t);
void* yyrealloc(void*, yy_size_t);
void yyfree(void*);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

FILE* yyin = NULL, * yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char* yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state(void);
static yy_state_type yy_try_NUL_trans(yy_state_type current_state);
static int yy_get_next_buffer(void);
static void yynoreturn yy_fatal_error(const char* msg);

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
 /* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
{
  flex_int32_t yy_verify;
  flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[512] =
{
0, 	63, 	63, 	63, 	63, 	63, 	63, 	67, 	65, 	63,
64, 	61, 	65, 	65, 	65, 	59, 	61, 	61, 	61, 	56,
61, 	61, 	61, 	61, 	61, 	61, 	61, 	54, 	61, 	61,
55, 	61, 	61, 	61, 	57, 	59, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	63, 	61, 	0,
59, 	60, 	0, 	61, 	59, 	61, 	61, 	35, 	61, 	61,
61, 	61, 	61, 	61, 	61, 	61, 	61, 	32, 	61, 	61,
61, 	61, 	61, 	61, 	61, 	61, 	61, 	61, 	61, 	61,
61, 	61, 	61, 	61, 	20, 	61, 	61, 	61, 	61, 	58,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	0, 	62, 	60,
45, 	61, 	0, 	61, 	61, 	61, 	61, 	04, 	61, 	61,
41, 	61, 	61, 	61, 	61, 	61, 	61, 	61, 	38, 	39,
61, 	61, 	61, 	61, 	61, 	29, 	28, 	61, 	61, 	61,
61, 	37, 	61, 	61, 	61, 	58, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	61, 	0, 	61, 	61, 	61, 	61, 	61, 	61, 	61,
61, 	61, 	61, 	30, 	12, 	61, 	61, 	61, 	52, 	61,
05, 	61, 	61, 	61, 	0, 	61, 	61, 	61, 	21, 	23,
61, 	27, 	49, 	61, 	07, 	61, 	61, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	61, 	0, 	61, 	61, 	61, 	61, 	61, 	61, 	61,
61, 	61, 	61, 	15, 	13, 	0, 	61, 	61, 	61, 	61,
61, 	61, 	0, 	61, 	61, 	06, 	36, 	25, 	61, 	50,
61, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	61, 	0,
61, 	61, 	53, 	61, 	61, 	61, 	61, 	61, 	61, 	61,
0, 	61, 	61, 	40, 	61, 	61, 	03, 	0, 	61, 	51,
61, 	61, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	61, 	0, 	0, 	61, 	61, 	61, 	61,
61, 	61, 	22, 	24, 	61, 	43, 	61, 	61, 	46, 	47,
0, 	01, 	61, 	42, 	02, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	02, 	02, 	01, 	02,
02, 	10, 	0, 	0, 	61, 	61, 	61, 	61, 	16, 	14,
26, 	61, 	61, 	0, 	61, 	02, 	02, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	02, 	61, 	0, 	0, 	31,
61, 	61, 	61, 	61, 	19, 	0, 	61, 	02, 	02, 	02,
02, 	02, 	02, 	02, 	02, 	9, 	0, 	0, 	61, 	61,
61, 	61, 	48, 	8, 	02, 	02, 	02, 	02, 	02, 	02,
33, 	34, 	17, 	61, 	61, 	61, 	02, 	02, 	02, 	02,
61, 	61, 	61, 	02, 	02, 	02, 	11, 	61, 	44, 	02,
02, 	02, 	18, 	02, 	0, 	0, 	0, 	0, 	0, 	0,
0, 	0

};

static const YY_CHAR yy_ec[256] =
{
0,         1,         1,         1,         1,         1,         1,         1,         1,         2,
3,         1,         1,         2,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         4,         1,         1,         1,         1,         1,         1,         1,
5,         5,         1,         1,         1,         6,         7,         8,         9,         9,
9,         9,         9,         9,         9,         9,         9,         9,         1,         1,
1,         1,         1,         1,         1,       0xA,       0xB,       0xC,       0xD,       0xE,
0xF,       0x10,       0x11,       0x12,         5,       0x13,       0x14,       0x15,       0x16,       0x17,
0x18,         5,       0x19,       0x1A,       0x1B,       0x1C,       0x1D,       0x1E,       0x1F,       0x20,
5,         1,         1,         1,         1,       0x21,         1,         5,         5,         5,
5,         5,         5,         5,         5,         5,         5,         5,         5,         5,
5,         5,         5,         5,         5,         5,         5,         5,         5,         5,
5,         5,         5,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1,         1,         1,         1,         1,
1,         1,         1,         1,         1,         1
};

static const YY_CHAR yy_meta[36] = {
 0,         1,         1,         1,         1,         2,         1,         2,         1,         2,
 2,         2,         2,         2,         2,         2,         2,         2,         2,         2,
 2,         2,         2,         2,         2,         2,         2,         2,         2,         2,
 2,         2,         2,         2,         0,         0
};

static const flex_int16_t yy_base[512] =
{
0, 	0, 	0, 	533, 	532, 	33, 	0, 	540, 	543, 	65,
543, 	0, 	61, 	530, 	530, 	64, 	52, 	52, 	519, 	514,
56, 	525, 	64, 	69, 	520, 	74, 	68, 	73, 	504, 	75,
71, 	77, 	510, 	517, 	0, 	83, 	0, 	92, 	83, 	81,
512, 	507, 	88, 	518, 	95, 	98, 	513, 	102, 	104, 	105,
497, 	107, 	103, 	109, 	503, 	510, 	0, 	129, 	0, 	514,
129, 	513, 	518, 	511, 	132, 	492, 	494, 	513, 	496, 	489,
489, 	500, 	481, 	488, 	483, 	493, 	488, 	0, 	108, 	493,
479, 	108, 	474, 	482, 	474, 	475, 	487, 	487, 	483, 	468,
484, 	482, 	485, 	480, 	0, 	130, 	468, 	465, 	479, 	143,
0, 	481, 	135, 	462, 	464, 	483, 	466, 	459, 	459, 	470,
451, 	458, 	453, 	463, 	458, 	0, 	132, 	463, 	449, 	130,
444, 	452, 	444, 	445, 	457, 	457, 	453, 	438, 	454, 	452,
455, 	450, 	0, 	137, 	438, 	435, 	449, 	457, 	543, 	450,
0, 	433, 	434, 	433, 	428, 	440, 	159, 	439, 	431, 	437,
0, 	437, 	426, 	434, 	423, 	426, 	418, 	135, 	0, 	0,
434, 	439, 	417, 	423, 	423, 	413, 	412, 	423, 	411, 	413,
412, 	0, 	411, 	414, 	404, 	141, 	421, 	0, 	404, 	405,
400, 	412, 	176, 	411, 	403, 	409, 	0, 	409, 	398, 	406,
395, 	398, 	390, 	138, 	0, 	0, 	406, 	411, 	389, 	395,
395, 	385, 	384, 	395, 	383, 	385, 	384, 	0, 	383, 	386,
376, 	379, 	376, 	388, 	376, 	386, 	373, 	368, 	377, 	384,
371, 	140, 	366, 	0, 	365, 	386, 	361, 	363, 	0, 	364,
0, 	368, 	367, 	366, 	372, 	367, 	371, 	353, 	0, 	0,
366, 	352, 	0, 	351, 	0, 	356, 	352, 	351, 	361, 	349,
359, 	346, 	341, 	350, 	357, 	344, 	146, 	339, 	0, 	338,
359, 	334, 	336, 	0, 	337, 	0, 	341, 	340, 	339, 	341,
345, 	327, 	0, 	0, 	340, 	326, 	0, 	325, 	0, 	330,
326, 	338, 	343, 	336, 	324, 	317, 	319, 	316, 	310, 	313,
309, 	325, 	327, 	0, 	0, 	326, 	313, 	322, 	311, 	306,
310, 	317, 	315, 	308, 	307, 	0, 	0, 	0, 	308, 	0,
300, 	314, 	313, 	301, 	294, 	296, 	293, 	287, 	290, 	286,
302, 	304, 	0, 	0, 	291, 	300, 	289, 	284, 	288, 	295,
287, 	286, 	0, 	0, 	0, 	287, 	0, 	279, 	291, 	166,
275, 	286, 	0, 	275, 	272, 	284, 	283, 	270, 	269, 	269,
266, 	279, 	277, 	0, 	263, 	275, 	0, 	273, 	255, 	0,
259, 	259, 	272, 	256, 	267, 	0, 	256, 	253, 	265, 	264,
251, 	250, 	250, 	261, 	259, 	0, 	245, 	257, 	0, 	238,
0, 	242, 	242, 	250, 	255, 	251, 	250, 	245, 	239, 	238,
234, 	233, 	0, 	0, 	232, 	543, 	245, 	232, 	0, 	0,
232, 	0, 	236, 	0, 	236, 	238, 	233, 	227, 	226, 	222,
221, 	0, 	0, 	220, 	233, 	220, 	0, 	0, 	0, 	225,
0, 	228, 	218, 	220, 	226, 	207, 	227, 	215, 	0, 	0,
0, 	212, 	207, 	208, 	209, 	217, 	217, 	198, 	218, 	206,
0, 	0, 	0, 	203, 	198, 	201, 	197, 	193, 	198, 	0,
206, 	207, 	203, 	189, 	0, 	202, 	193, 	188, 	0, 	199,
200, 	196, 	182, 	0, 	187, 	0, 	194, 	177, 	180, 	188,
182, 	174, 	543, 	0, 	0, 	172, 	180, 	178, 	170, 	0,
543, 	543, 	0, 	180, 	162, 	164, 	0, 	175, 	156, 	157,
156, 	167, 	166, 	153, 	164, 	158, 	0, 	144, 	0, 	0,
134, 	0, 	0, 	0, 	543, 	155, 	152, 	202, 	0, 	0,
0, 	0

};

static const flex_int16_t yy_def[512] =
{
0, 	504, 	01, 	01, 	01, 	504, 	05, 	504, 	504, 	504,
504, 	505, 	504, 	504, 	504, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	504, 	505, 	504,
504, 	504, 	507, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	507, 	504, 	505,
505, 	505, 	504, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	505, 	504, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	504, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	505, 	504, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	504, 	505, 	505, 	505, 	505,
505, 	505, 	504, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	505, 	504,
505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505, 	505,
504, 	505, 	505, 	505, 	505, 	505, 	505, 	504, 	505, 	505,
505, 	505, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	505, 	504, 	504, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	505, 	505, 	504, 	505, 	505, 	505, 	505,
504, 	505, 	505, 	505, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506, 	506,
506, 	505, 	504, 	504, 	505, 	505, 	505, 	505, 	505, 	505,
505, 	505, 	505, 	504, 	505, 	506, 	506, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	506, 	505, 	504, 	504, 	505,
505, 	505, 	505, 	505, 	505, 	504, 	505, 	506, 	506, 	506,
506, 	506, 	506, 	506, 	506, 	505, 	504, 	504, 	505, 	505,
505, 	505, 	504, 	505, 	506, 	506, 	506, 	506, 	506, 	506,
504, 	504, 	505, 	505, 	505, 	505, 	506, 	506, 	506, 	506,
505, 	505, 	505, 	506, 	506, 	506, 	505, 	505, 	505, 	506,
506, 	506, 	505, 	506, 	0, 	504, 	504, 	504, 	0, 	0,
0, 	0



};

static const flex_int16_t yy_nxt[584] =
{ 0, 	8,  9, 	10, 	9, 	11, 	12, 	13, 	14, 	15,
16, 	11, 	17, 	18, 	19, 	20, 	21, 	22, 	23, 	24,
25, 	26, 	27, 	28, 	11, 	29, 	30, 	31, 	32, 	33,
34, 	11, 	11, 	8, 	8, 	9, 	10, 	9, 	36, 	12,
13, 	14, 	37, 	38, 	36, 	39, 	40, 	41, 	42, 	43,
44, 	45, 	46, 	47, 	48, 	49, 	50, 	36, 	51, 	52,
53, 	54, 	55, 	56, 	36, 	36, 	8, 	57, 	59, 	57,
60, 	63, 	65, 	64, 	72, 	68, 	66, 	75, 	82, 	67,
69, 	73, 	77, 	84, 	80, 	87, 	83, 	76, 	81, 	90,
63, 	78, 	99, 	88, 	93, 	91, 	85, 	89, 	92, 	101,
94, 	102, 	95, 	103, 	106, 	96, 	110, 	104, 	113, 	107,
105, 	115, 	118, 	111, 	120, 	122, 	119, 	125, 	114, 	152,
116, 	128, 	121, 	156, 	157, 	126, 	131, 	129, 	123, 	127,
130, 	57, 	132, 	57, 	133, 	153, 	59, 	134, 	60, 	63,
170, 	64, 	101, 	188, 	102, 	192, 	193, 	206, 	231, 	171,
63, 	266, 	64, 	175, 	100, 	175, 	207, 	58, 	291, 	189,
503, 	175, 	232, 	175, 	320, 	267, 	175, 	292, 	175, 	216,
502, 	217, 	501, 	321, 	218, 	219, 	384, 	385, 	500, 	499,
498, 	497, 	496, 	495, 	220, 	221, 	251, 	494, 	252, 	493,
492, 	253, 	254, 	491, 	490, 	489, 	488, 	487, 	486, 	485,
484, 	255, 	256, 	137, 	137, 	483, 	482, 	481, 	480, 	479,
478, 	477, 	476, 	475, 	474, 	473, 	472, 	471, 	470, 	469,
468, 	467, 	466, 	465, 	464, 	463, 	462, 	461, 	460, 	459,
458, 	457, 	456, 	455, 	454, 	453, 	452, 	451, 	450, 	449,
448, 	447, 	446, 	445, 	444, 	443, 	442, 	441, 	440, 	439,
438, 	437, 	436, 	435, 	434, 	433, 	432, 	431, 	430, 	429,
428, 	427, 	426, 	425, 	424, 	423, 	422, 	421, 	420, 	419,
418, 	417, 	416, 	415, 	414, 	413, 	412, 	411, 	410, 	409,
408, 	407, 	406, 	405, 	404, 	403, 	402, 	401, 	400, 	399,
398, 	397, 	396, 	395, 	394, 	393, 	392, 	391, 	390, 	389,
388, 	387, 	386, 	383, 	382, 	381, 	380, 	379, 	378, 	377,
376, 	375, 	374, 	373, 	372, 	371, 	370, 	369, 	368, 	367,
366, 	365, 	364, 	363, 	362, 	361, 	360, 	359, 	358, 	357,
356, 	355, 	354, 	353, 	352, 	351, 	350, 	349, 	348, 	347,
346, 	345, 	344, 	343, 	342, 	341, 	340, 	339, 	338, 	337,
336, 	335, 	334, 	333, 	332, 	331, 	330, 	329, 	328, 	327,
326, 	325, 	324, 	295, 	323, 	322, 	319, 	318, 	317, 	316,
315, 	314, 	313, 	312, 	311, 	310, 	309, 	308, 	307, 	306,
305, 	304, 	303, 	302, 	301, 	300, 	299, 	298, 	297, 	296,
295, 	294, 	293, 	290, 	289, 	288, 	287, 	286, 	285, 	284,
283, 	282, 	281, 	280, 	279, 	278, 	277, 	276, 	275, 	274,
273, 	272, 	271, 	270, 	269, 	234, 	268, 	265, 	264, 	263,
262, 	261, 	260, 	259, 	258, 	257, 	250, 	249, 	248, 	247,
176, 	246, 	245, 	244, 	243, 	242, 	241, 	240, 	239, 	238,
237, 	236, 	235, 	234, 	233, 	230, 	229, 	228, 	227, 	226,
225, 	224, 	223, 	222, 	215, 	214, 	213, 	212, 	211, 	139,
138, 	210, 	209, 	208, 	205, 	204, 	203, 	202, 	201, 	200,
199, 	198, 	197, 	196, 	195, 	194, 	191, 	190, 	187, 	186,
185, 	184, 	183, 	182, 	181, 	180, 	179, 	142, 	178, 	177,
176, 	174, 	173, 	172, 	169, 	168, 	167, 	166, 	165, 	164,
163, 	162, 	161, 	160, 	159, 	158, 	155, 	154, 	151, 	150,
149, 	148, 	147, 	146, 	145, 	144, 	143, 	142, 	141, 	140,
139, 	138, 	61, 	61, 	136, 	135, 	124, 	117, 	112, 	109,
108, 	98, 	97, 	86, 	79, 	74, 	71, 	70, 	62, 	61,
504, 	35, 	35, 	07, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	0,	0,	0,
0,	0,	0,	0



};

static const flex_int16_t yy_chk[584] =
{
0, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01,
01, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01,
01, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01, 	01,
01, 	01, 	01, 	01, 	05, 	05, 	05, 	05, 	05, 	05,
05, 	05, 	05, 	05, 	05, 	05, 	05, 	05, 	05, 	05,
05, 	05, 	05, 	05, 	05, 	05, 	05, 	05, 	05, 	05,
05, 	05, 	05, 	05, 	05, 	05, 	05, 	9, 	12, 	9,
12, 	15, 	16, 	15, 	20, 	17, 	16, 	22, 	26, 	16,
17, 	20, 	23, 	27, 	25, 	29, 	26, 	22, 	25, 	30,
35, 	23, 	35, 	29, 	31, 	30, 	27, 	29, 	30, 	37,
31, 	37, 	31, 	38, 	39, 	31, 	42, 	38, 	44, 	39,
38, 	45, 	47, 	42, 	48, 	49, 	47, 	51, 	44, 	78,
45, 	52, 	48, 	81, 	81, 	51, 	53, 	52, 	49, 	51,
52, 	57, 	53, 	57, 	53, 	78, 	60, 	53, 	60, 	64,
95, 	64, 	102, 	116, 	102, 	119, 	119, 	133, 	157, 	95,
99, 	193, 	99, 	175, 	506, 	99, 	133, 	505, 	221, 	116,
500, 	175, 	157, 	99, 	256, 	193, 	175, 	221, 	99, 	146,
497, 	146, 	495, 	256, 	146, 	146, 	339, 	339, 	494, 	493,
492, 	491, 	490, 	489, 	146, 	146, 	182, 	488, 	182, 	487,
485, 	182, 	182, 	484, 	483, 	478, 	477, 	476, 	475, 	471,
470, 	182, 	182, 	507, 	507, 	469, 	468, 	467, 	466, 	464,
462, 	461, 	460, 	459, 	457, 	456, 	455, 	453, 	452, 	451,
450, 	448, 	447, 	446, 	445, 	444, 	443, 	439, 	438, 	437,
436, 	435, 	434, 	433, 	432, 	431, 	427, 	426, 	425, 	424,
423, 	422, 	421, 	419, 	415, 	414, 	413, 	410, 	409, 	408,
407, 	406, 	405, 	404, 	402, 	400, 	397, 	396, 	394, 	391,
390, 	389, 	388, 	387, 	386, 	385, 	384, 	383, 	382, 	381,
379, 	377, 	376, 	374, 	373, 	372, 	371, 	370, 	369, 	368,
367, 	366, 	364, 	363, 	362, 	361, 	360, 	358, 	357, 	355,
354, 	352, 	351, 	350, 	349, 	348, 	347, 	346, 	345, 	344,
343, 	341, 	340, 	338, 	337, 	335, 	331, 	330, 	329, 	328,
327, 	326, 	325, 	324, 	321, 	320, 	319, 	318, 	317, 	316,
315, 	314, 	313, 	312, 	311, 	310, 	308, 	304, 	303, 	302,
301, 	300, 	299, 	298, 	297, 	296, 	295, 	292, 	291, 	290,
289, 	288, 	287, 	286, 	285, 	284, 	283, 	282, 	281, 	280,
279, 	277, 	275, 	274, 	271, 	270, 	269, 	268, 	267, 	266,
264, 	262, 	261, 	260, 	259, 	257, 	255, 	254, 	253, 	252,
251, 	250, 	249, 	248, 	247, 	246, 	245, 	243, 	241, 	240,
237, 	236, 	235, 	234, 	233, 	232, 	231, 	229, 	227, 	226,
225, 	224, 	222, 	220, 	219, 	218, 	217, 	216, 	215, 	214,
213, 	212, 	211, 	210, 	209, 	208, 	206, 	205, 	204, 	203,
202, 	201, 	200, 	199, 	198, 	197, 	196, 	192, 	191, 	190,
189, 	188, 	187, 	185, 	184, 	183, 	181, 	180, 	179, 	178,
176, 	174, 	173, 	172, 	170, 	169, 	168, 	167, 	166, 	165,
164, 	163, 	162, 	161, 	160, 	156, 	155, 	154, 	153, 	152,
151, 	149, 	148, 	147, 	145, 	144, 	143, 	142, 	141, 	139,
137, 	136, 	135, 	134, 	131, 	130, 	129, 	128, 	127, 	126,
125, 	124, 	123, 	122, 	121, 	120, 	118, 	117, 	114, 	113,
112, 	111, 	110, 	109, 	108, 	107, 	106, 	105, 	104, 	103,
101, 	98, 	97, 	96, 	93, 	92, 	91, 	90, 	89, 	88,
87, 	86, 	85, 	84, 	83, 	82, 	80, 	79, 	76, 	75,
74, 	73, 	72, 	71, 	70, 	69, 	68, 	67, 	66, 	65,
63, 	62, 	61, 	59, 	55, 	54, 	50, 	46, 	43, 	41,
40, 	33, 	32, 	28, 	24, 	21, 	19, 	18, 	14, 	13,
07, 	04, 	03, 	504, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504, 	504,
504, 	504, 	504, 	504, 	504, 	504, 	504, 	0, 	0, 	0,
0, 	0, 	0, 	0


};

static yy_state_type yy_last_accepting_state;
static char* yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static const flex_int16_t yy_rule_linenum[70] =
{ 0,
  110,  111,  112,  113,  114,  115,  119,  121,  122,  123,
  124,  125,  126,  127,  128,  129,  131,  132,  133,  134,
  135,  137,  138,  139,  140,  153,  154,  155,  156,  157,
  158,  166,  167,  168,  170,  171,  179,  183,  184,  185,
  186,  187,  188,  189,  190,  191,  215,  225,  226,  227,
  246,  247,  257,  267,  268,  270,  272,  273,  274,  275,
  276,  277,  279,  280,  281,  282,  283,  284,  285
};

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char* yytext;
#include <windows.h>
#include <winnt.h>
#include <array>
#include <vector>
#include <stdio.h>
//#include "RobotTokens.h"
#include <math.h>
#include "sidstar.tab.h"
#include <string>

//#include <sidstar_tokens.h>
//#include <stdafx.h>

// Flex использует макрос YY_DECL как основу объявления функции, сканирующей следующий токен.
// По умолчанию значение макроса YY_DECL равно `int yylex()`
// Но мы назовём функцию ScanToken.
#define YY_DECL int ScanToken()
#define fileno _fileno
#define isatty _isatty
int sign;
float lat, lon;

/*enum TYPEROUTE
{
  NONE,
  FIX,
  FIXOVERFY,
  HDGINTERCEPTTOFIX,
  HDGINTERCEPTFROMFIX,
  TRKINTERCEPTTOFIX,
  TRKINTERCEPTFROMFIX,
  TURNRIGHT,
  TURNLEFT,
  TURNRIGHTOVERFLY,
  TURNLEFTOVERFLY,
  TRKUNTIL,
  TRKUNTILFROMFIX,
  HDGUNTIL,
  HDGVECTORS,
  RNW,

};*/
/*enum ALT
{
  AT,
  ATORABOVE,
  ATORBELOW,
  ABOVEBELOW,
};*/

struct sfix
{
  std::string name;
  float lat;
  float lon;
} pfix;
struct sroute
{
  int type;
  int alttype;
  float alt;
  float alt2;
  float speed;
  float radial;
  float trk;
  float hdg;
  float dist;
  float legtime;
  std::string name;
} proute;
struct srnwsid
{
  std::string name;
  std::vector<sroute>* eroute;

} prnwsid;
struct ssid
{
  std::string name;
  std::vector<srnwsid>* ernws;
  std::vector<srnwsid>* etrans;
  std::vector<std::string>* ernw;
} psid;
struct ssidstar
{
  std::vector<sfix>* efixes;
  std::vector<ssid>* esids;
  std::vector<ssid>* estars;
  std::vector<ssid>* eapproaches;
} sidstar2;
std::vector<srnwsid>* PointVector;
std::vector<sroute>* vRoute = NULL;
std::vector<sfix>* vFix = NULL;
enum MODE
{
  ESIDS,
  ESTARS,
  EAPPROACHES,
};
int mode = 0;
std::string stemp;

#define INITIAL 0
#define fixes 1
#define fix 2
#define latlon 3
#define ns 4
#define ew 5
#define degreeslat 6
#define degreeslon 7
#define rnws 8
#define rnw 9
#define sids 10
#define sid 11
#define sidtrans 12
#define sidrun 13
#define croute 14
#define fixroute 15
#define routealt 16
#define fixspeed 17
#define trkroute 18
#define hdgroute 19
#define routeradial 20
#define routeradialfix 21
#define routeuntil 22
#define trkrouteradial 23
#define stars 24
#define star 25
#define starrnw 26
#define rnwroute 27
#define approach 28
#define approaches 29
#define trkuntilfrom 30

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
 /* %if-c-only */
#include <unistd.h>
/* %endif */
/* %if-c++-only */
/* %endif */
#endif
#include <locale.h>

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals(void);

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy(void);

int yyget_debug(void);

void yyset_debug(int debug_flag);

YY_EXTRA_TYPE yyget_extra(void);

void yyset_extra(YY_EXTRA_TYPE user_defined);

FILE* yyget_in(void);

void yyset_in(FILE* _in_str);

FILE* yyget_out(void);

void yyset_out(FILE* _out_str);

int yyget_leng(void);

char* yyget_text(void);

int yyget_lineno(void);

void yyset_lineno(int _line_number);

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap(void);
#else
extern int yywrap(void);
#endif
#endif

/* %not-for-header */
#ifndef YY_NO_UNPUT

static void yyunput(int c, char* buf_ptr);

#endif
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy(char*, const char*, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char*);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
#ifdef __cplusplus
static int yyinput(void);
#else
static int input(void);
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
 /* %endif */
 /* %if-c++-only C++ definition */
 /* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

 /* No semi-colon after return; correct usage is to write "yyterminate();" -
  * we don't want an extra ';' after the "return" because that will cause
  * some compilers to complain about unreachable statements.
  */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

  /* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
 /* %if-c-only Standard (non-C++) definition */

extern int yylex(void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

 /* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
  main1:
  yy_state_type yy_current_state;
  char* yy_cp,* yy_bp;
  int yy_act;

  if (!(yy_init))
    {
    (yy_init) = 1;

#ifdef YY_USER_INIT
    YY_USER_INIT;
#endif

    if (!(yy_start))
      (yy_start) = 1;	/* first start state */

    if (!yyin)
      /* %if-c-only */
            yyin = stdin;
    /* %endif */
    /* %if-c++-only */
    /* %endif */

        if (!yyout)
          /* %if-c-only */
                yyout = stdout;
        /* %endif */
        /* %if-c++-only */
        /* %endif */

            if (!YY_CURRENT_BUFFER) {
              yyensure_buffer_stack();
              YY_CURRENT_BUFFER_LVALUE =
                yy_create_buffer(yyin, YY_BUF_SIZE);
            }

            yy_load_buffer_state();
            }

          {
    /* %% [7.0] user's declarations go here */

      while ( /*CONSTCOND*/1)		/* loops until end-of-file is reached */
        {
        /* %% [8.0] yymore()-related code goes here */
            yy_cp = (yy_c_buf_p);

            /* Support of yytext. */
            *yy_cp = (yy_hold_char);

            /* yy_bp points to the position in yy_ch_buf of the start of
             * the current run.
             */
            yy_bp = yy_cp;

            /* %% [9.0] code to set up and find next match goes here */
                yy_current_state = (yy_start);
            yy_match:
                do
                  {
                  YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                  if (yy_accept[yy_current_state])
                    {
                    (yy_last_accepting_state) = yy_current_state;
                    (yy_last_accepting_cpos) = yy_cp;
                    }
                  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
                    {
                    yy_current_state = (int)yy_def[yy_current_state];
                    if (yy_current_state >= 505)
                      yy_c = yy_meta[yy_c];
                    }
                  yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
                  ++yy_cp;
                  } while (yy_base[yy_current_state] != 543);

            yy_find_action:
                  /* %% [10.0] code to find the action number goes here */
                      yy_act = yy_accept[yy_current_state];
                      if (yy_act == 0)
                        { /* have to back up */
                        yy_cp = (yy_last_accepting_cpos);
                        yy_current_state = (yy_last_accepting_state);
                        yy_act = yy_accept[yy_current_state];
                        }

                      YY_DO_BEFORE_ACTION;

                      /* %% [11.0] code for yylineno update goes here */

                      do_action:	/* This label is used only to access EOF actions. */

                      /* %% [12.0] debug code goes here */
                        /*  if (yy_flex_debug)
                            {
                            if (yy_prev != yy_start)
                            {
                              yy_prev = yy_start;
                              fprintf(stderr, "BEGIN<%d>\n", long((yy_start - 1) / 2));
                            }
                            if (yy_act == 0)
                              fprintf(stderr, "--scanner backing up\n");
                            else if (yy_act == 62) {}

                            else if (yy_act == 63) {}

                            else if (yy_act == 64) {}

                            else if (yy_act < 67)

                              fprintf(stderr, "--accepting rule at line %ld (\"%s\")\n",
                                       (long)yy_act, yytext);
                            else if (yy_act == 67)
                              fprintf(stderr, "--accepting default rule (\"%s\")\n",
                                       yytext);
                            else if (yy_act == 70)
                              fprintf(stderr, "--(end of buffer or a NUL)\n");
                            else
                              fprintf(stderr, "--EOF (start condition %d)\n", YY_START);
                            }*/

                          switch (yy_act)
                        { /* beginning of action switch */
                      /* %% [13.0] actions go here */
                            case 0: /* must back up */
                            /* undo the effects of YY_DO_BEFORE_ACTION */
                            *yy_cp = (yy_hold_char);
                            yy_cp = (yy_last_accepting_cpos);
                            yy_current_state = (yy_last_accepting_state);
                            goto yy_find_action;

                      case 1:
                        /* rule 1 can match eol */
                        YY_RULE_SETUP
                        return 0x104;
                          YY_BREAK
                        case 2:
                          /* rule 2 can match eol */
                            YY_RULE_SETUP
                              BEGIN(0);
                            yylval.string = strdup(yytext);
                            return 0x11b;
                            YY_BREAK
                          case 3:
                            /* rule 3 can match eol */
                            YY_RULE_SETUP
                            BEGIN(2);
                            return 0x11c;
                              YY_BREAK
                            case 4:
                              /* FIX*/
                              YY_RULE_SETUP
                              BEGIN(2);
                              return 0x11c;
                                YY_BREAK
                              case 5:
                                /* rule 5 can match eol */
                                YY_RULE_SETUP
                                return 0x101;
                                  YY_BREAK
                                case 6:
                                YY_RULE_SETUP
                                return 0x102;
                                  YY_BREAK
                                case 7:
                                YY_RULE_SETUP
                                return 0x103;
                                  YY_BREAK
                                case 8:
                                YY_RULE_SETUP
                                BEGIN(2);
                                return 0x105;
                                  YY_BREAK
                                case 9:
                                YY_RULE_SETUP
                                return 0x107;
                                  YY_BREAK
                                case 10:
                                YY_RULE_SETUP
                                BEGIN(2);
                                return 0x108;
                                  YY_BREAK
                                case 11:
                                YY_RULE_SETUP
                                return 0x106;
                                  YY_BREAK
                                case 12:
                                YY_RULE_SETUP
                                return 0x109;
                                  YY_BREAK
                                case 13:
                                YY_RULE_SETUP
                                return 0x10A;
                                  YY_BREAK
                                case 14:
                                YY_RULE_SETUP
                                return 0x10B;
                                  YY_BREAK
                                case 15:
                                  /* FIXES */
                                  YY_RULE_SETUP
                                    return 0x10e;
                                  YY_BREAK
                                case 16:
                                YY_RULE_SETUP
                                return 0x110;
                                  YY_BREAK
                                case 17:
                                YY_RULE_SETUP
                                return 0x10C;
                                  YY_BREAK
                                case 18:
                                YY_RULE_SETUP
                                return 0x10D;
                                  YY_BREAK
                                case 19:
                                YY_RULE_SETUP
                                return 0x12C;
                                  YY_BREAK
                                case 20:
                                YY_RULE_SETUP
                                return 0x12B;
                                  YY_BREAK
                                case 21:
                                YY_RULE_SETUP
                                return 0x117;
                                  YY_BREAK
                                case 22:
                                YY_RULE_SETUP
                                return 0x11A;
                                  YY_BREAK
                                case 23:
                                YY_RULE_SETUP
                                return 0x111;
                                  YY_BREAK
                                case 24:
                                YY_RULE_SETUP
                                return 0x113;
                                  YY_BREAK
                                case 25:
                                YY_RULE_SETUP
                                return 0x114;
                                  YY_BREAK
                                case 26:
                                YY_RULE_SETUP
                                return 0x116;
                                YY_BREAK
                                case 27:
                                YY_RULE_SETUP
                                BEGIN(2);
                                return 0x115;
                                  YY_BREAK
                                case 28:
                                YY_RULE_SETUP
                                BEGIN(2);
                                return 0x112;
                                  YY_BREAK
                                case 29:
                                YY_RULE_SETUP
                                BEGIN(1);
                                return 0x118;
                                  YY_BREAK
                                case 30:
                                YY_RULE_SETUP
                                return 0x120;
                                  YY_BREAK
                                case 31:
                                YY_RULE_SETUP
                                BEGIN(2);
                                return 0x11F;
                                  YY_BREAK
                                case 32:
                                YY_RULE_SETUP
                                return 0x11E;
                                  YY_BREAK
                                case 33:
                                YY_RULE_SETUP
                                return 0x122;
                                  YY_BREAK
                                case 34:
                                YY_RULE_SETUP
                                return 0x123;
                                  YY_BREAK
                                case 35:
                                YY_RULE_SETUP
                                return 0x121;
                                  YY_BREAK
                                case 36:
                                YY_RULE_SETUP
                                return 0x138;
                                case 37:
                                YY_RULE_SETUP
                                return 0x139;
                                  YY_BREAK
                                case 38:
                                YY_RULE_SETUP
                                return 0x124;
                                  YY_BREAK
                                case 39:
                                YY_RULE_SETUP
                                return 0x125;
                                  YY_BREAK
                                case 40:
                                YY_RULE_SETUP
                                return 0x126;
                                  YY_BREAK
                                case 41:
                                YY_RULE_SETUP
                                return 0x12A;
                                  YY_BREAK
                                case 42:
                                YY_RULE_SETUP
                                return 0x12E;
                                  YY_BREAK
                                case 43:
                                YY_RULE_SETUP
                                return 0x12F;
                                  YY_BREAK
                                case 44:
                                YY_RULE_SETUP
                                return 0x130;
                                  YY_BREAK
                                case 45:
                                YY_RULE_SETUP
                                return 0x131;
                                  YY_BREAK
                                case 46:
                                  /* rule 46 can match eol */
                                  YY_RULE_SETUP
                                  return 0x132;
                                    YY_BREAK
                                  case 47:
                                  YY_RULE_SETUP
                                  return 0x133;
                                    YY_BREAK
                                  case 48:
                                  YY_RULE_SETUP
                                  return 0x129;
                                    YY_BREAK
                                  case 49:
                                  YY_RULE_SETUP
                                  return 0x134;
                                    YY_BREAK
                                  case 50:
                                  YY_RULE_SETUP
                                  return 0x12D;
                                    YY_BREAK
                                  case 51:
                                  YY_RULE_SETUP
                                  return 0x137;
                                    YY_BREAK
                                  case 52:
                                  YY_RULE_SETUP
                                  return 0x135;
                                    YY_BREAK
                                  case 53:
                                  YY_RULE_SETUP
                                  return 0x136;
                                    YY_BREAK
                                  case 54:
                                  YY_RULE_SETUP
                                    yylval.string = strdup(yytext);
                                  return 0x127;
                                    YY_BREAK
                                  case 55:
                                  YY_RULE_SETUP
                                    yylval.string = strdup(yytext);
                                  return 0x127;
                                    YY_BREAK
                                  case 56:
                                    YY_RULE_SETUP
                                      yylval.string = strdup(yytext);
                                  return 0x128;
                                    YY_BREAK
                                  case 57:
                                  YY_RULE_SETUP
                                    yylval.string = strdup(yytext);
                                  return 0x128;
                                    YY_BREAK
                                  case 58:
                                    YY_RULE_SETUP
                                      BEGIN(0);
                                      yylval.string = strdup(yytext);
                                  return 0x119;
                                    YY_BREAK
                                  case 59:
                                    YY_RULE_SETUP
                                      setlocale(LC_ALL, "english");
                                      yylval.flo = std::atof(yytext);
                                  return 0x11D;
                                    YY_BREAK
                                  case 60:
                                  YY_RULE_SETUP
                                    setlocale(LC_ALL, "english");
                                    yylval.flo = std::atof(yytext);
                                  return 0x11D;
                                    YY_BREAK
                                  case 61:
                                  YY_RULE_SETUP
                                    yylval.string = strdup(yytext);
                                  return 0x11B;
                                    YY_BREAK
                                  case 62:
                                    //Comments
                                  YY_RULE_SETUP

                                    YY_BREAK
                                  case 63:
                                  YY_RULE_SETUP

                                    YY_BREAK
                                  case 64:
                                  YY_RULE_SETUP

                                    YY_BREAK
                                  case 65:
                                  YY_RULE_SETUP
                                    //Error

                                      YY_BREAK
                                    case 66:
                                    YY_RULE_SETUP
                                    ECHO;
                                      YY_BREAK
                                    case YY_STATE_EOF(0):
                                    case YY_STATE_EOF(1):
                                    case YY_STATE_EOF(2):

                                      yyterminate();

                                      case YY_END_OF_BUFFER:
                                        {
                                        /* Amount of text matched not including the EOB char. */
                                        int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

                                        /* Undo the effects of YY_DO_BEFORE_ACTION. */
                                        *yy_cp = (yy_hold_char);
                                        YY_RESTORE_YY_MORE_OFFSET

                                        if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW)
                                          {
                                          /* We're scanning a new file or input source.  It's
                                           * possible that this happened because the user
                                           * just pointed yyin at a new source and called
                                           * yylex().  If so, then we have to assure
                                           * consistency between YY_CURRENT_BUFFER and our
                                           * globals.  Here is the right place to do so, because
                                           * this is the first action (other than possibly a
                                           * back-up) that will match for the new input source.
                                           */
                                          (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                                          /* %if-c-only */
                                                YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
                                                /* %endif */
                                                /* %if-c++-only */
                                                /* %endif */
                                                      YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                                                      }

                                        /* Note that here we test for yy_c_buf_p "<=" to the position
                                         * of the first EOB in the buffer, since yy_c_buf_p will
                                         * already have been incremented past the NUL character
                                         * (since all states make transitions on EOB to the
                                         * end-of-buffer state).  Contrast this with the test
                                         * in input().
                                         */
                                        if ((yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
                                          { /* This was really a NUL. */
                                          yy_state_type yy_next_state;

                                          (yy_c_buf_p) = (yytext_ptr)+yy_amount_of_matched_text;

                                          yy_current_state = yy_get_previous_state();

                                          /* Okay, we're now positioned to make the NUL
                                           * transition.  We couldn't have
                                           * yy_get_previous_state() go ahead and do it
                                           * for us because it doesn't know how to deal
                                           * with the possibility of jamming (and we don't
                                           * want to build jamming into it because then it
                                           * will run more slowly).
                                           */

                                          yy_next_state = yy_try_NUL_trans(yy_current_state);

                                          yy_bp = (yytext_ptr)+YY_MORE_ADJ;

                                          if (yy_next_state)
                                            {
                                            /* Consume the NUL. */
                                            yy_cp = ++(yy_c_buf_p);
                                            yy_current_state = yy_next_state;
                                            goto yy_match;
                                            }

                                          else
                                            {
                                            /* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
                                                    yy_cp = (yy_c_buf_p);
                                                    goto yy_find_action;
                                                    }
                                                  }

                                                else switch (yy_get_next_buffer())
                                                  {
                                                  case EOB_ACT_END_OF_FILE:
                                                    {
                                                    (yy_did_buffer_switch_on_eof) = 0;

                                                    if (yywrap())
                                                      {
                                                      /* Note: because we've taken care in
                                                       * yy_get_next_buffer() to have set up
                                                       * yytext, we can now set up
                                                       * yy_c_buf_p so that if some total
                                                       * hoser (like flex itself) wants to
                                                       * call the scanner after we return the
                                                       * YY_NULL, it'll still work - another
                                                       * YY_NULL will get returned.
                                                       */
                                                      (yy_c_buf_p) = (yytext_ptr)+YY_MORE_ADJ;

                                                      yy_act = YY_STATE_EOF(YY_START);
                                                      goto do_action;
                                                      }

                                                    else
                                                      {
                                                      if (!(yy_did_buffer_switch_on_eof))
                                                        YY_NEW_FILE;
                                                      }
                                                    break;
                                                    }

                                                  case EOB_ACT_CONTINUE_SCAN:
                                                    (yy_c_buf_p) =
                                                      (yytext_ptr)+yy_amount_of_matched_text;

                                                    yy_current_state = yy_get_previous_state();

                                                    yy_cp = (yy_c_buf_p);
                                                    yy_bp = (yytext_ptr)+YY_MORE_ADJ;
                                                    goto yy_match;

                                                  case EOB_ACT_LAST_MATCH:
                                                    (yy_c_buf_p) =
                                                    &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

                                                    yy_current_state = yy_get_previous_state();

                                                    yy_cp = (yy_c_buf_p);
                                                    yy_bp = (yytext_ptr)+YY_MORE_ADJ;
                                                    goto yy_find_action;
                                                  }
                                                break;
                                                }

                                              default:
                                                YY_FATAL_ERROR(
                                                  "fatal flex scanner internal error--no action found");
                                              } /* end of action switch */
                                                } /* end of scanning one token */
                                              } /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
 /* %if-c-only */
  static int yy_get_next_buffer(void)
  /* %endif */
  /* %if-c++-only */
  /* %endif */
{
  char* dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
  char* source = (yytext_ptr);
  int number_to_move, i;
  int ret_val;

  if ((yy_c_buf_p) > & YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1])
    YY_FATAL_ERROR(
      "fatal flex scanner internal error--end of buffer missed");

  if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0)
  { /* Don't try to fill the buffer, so this is an EOF. */
    if ((yy_c_buf_p)-(yytext_ptr)-YY_MORE_ADJ == 1)
    {
      /* We matched a single character, the EOB, so
       * treat this as a final EOF.
       */
      return EOB_ACT_END_OF_FILE;
    }

    else
    {
      /* We matched some text prior to the EOB, first
       * process it.
       */
      return EOB_ACT_LAST_MATCH;
    }
  }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int)((yy_c_buf_p)-(yytext_ptr)-1);

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

  else
  {
    int num_to_read =
      YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

    while (num_to_read <= 0)
    { /* Not enough room in the buffer - grow it. */

    /* just a shorter name for the current buffer */
      YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

      int yy_c_buf_p_offset =
        (int)((yy_c_buf_p)-b->yy_ch_buf);

      if (b->yy_is_our_buffer)
      {
        int new_size = b->yy_buf_size * 2;

        if (new_size <= 0)
          b->yy_buf_size += b->yy_buf_size / 8;
        else
          b->yy_buf_size *= 2;

        b->yy_ch_buf = (char*)
          /* Include room in for 2 EOB chars. */
          yyrealloc((void*)b->yy_ch_buf,
          (yy_size_t)(b->yy_buf_size + 2));
      }
      else
        /* Can't grow it, we don't own it. */
        b->yy_ch_buf = NULL;

      if (!b->yy_ch_buf)
        YY_FATAL_ERROR(
          "fatal error - scanner input buffer overflow");

      (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

      num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
        number_to_move - 1;

    }

    if (num_to_read > YY_READ_BUF_SIZE)
      num_to_read = YY_READ_BUF_SIZE;

    /* Read in more data. */
    YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
      (yy_n_chars), num_to_read);

    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  if ((yy_n_chars) == 0)
  {
    if (number_to_move == YY_MORE_ADJ)
    {
      ret_val = EOB_ACT_END_OF_FILE;
      yyrestart(yyin);
    }

    else
    {
      ret_val = EOB_ACT_LAST_MATCH;
      YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
        YY_BUFFER_EOF_PENDING;
    }
  }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  if (((yy_n_chars)+number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
    /* Extend the array by 50%, plus the number we really need. */
    int new_size = (yy_n_chars)+number_to_move + ((yy_n_chars) >> 1);
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char*)yyrealloc(
      (void*)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t)new_size);
    if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
      YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
    /* "- 2" to take care of EOB's */
    YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size - 2);
  }

  (yy_n_chars) += number_to_move;
  YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
  YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)+1] = YY_END_OF_BUFFER_CHAR;

  (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

  return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
static yy_state_type yy_get_previous_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  yy_state_type yy_current_state;
  char* yy_cp;

  /* %% [15.0] code to get the start state into yy_current_state goes here */
  yy_current_state = (yy_start);

  for (yy_cp = (yytext_ptr)+YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp)
  {
    /* %% [16.0] code to find the next state goes here */
    YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
    if (yy_accept[yy_current_state])
    {
      (yy_last_accepting_state) = yy_current_state;
      (yy_last_accepting_cpos) = yy_cp;
    }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int)yy_def[yy_current_state];
      if (yy_current_state >= 483)
        yy_c = yy_meta[yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
  }

  return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
 /* %if-c-only */
static yy_state_type yy_try_NUL_trans(yy_state_type yy_current_state)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  int yy_is_jam;
  /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
  char* yy_cp = (yy_c_buf_p);

  YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
  {
    (yy_last_accepting_state) = yy_current_state;
    (yy_last_accepting_cpos) = yy_cp;
  }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
  {
    yy_current_state = (int)yy_def[yy_current_state];
    if (yy_current_state >= 483)
      yy_c = yy_meta[yy_c];
  }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
  yy_is_jam = (yy_current_state == 482);

  return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */

static void yyunput(int c, char* yy_bp)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  char* yy_cp;

  yy_cp = (yy_c_buf_p);

  /* undo effects of setting up yytext */
  *yy_cp = (yy_hold_char);

  if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
  { /* need to shift things up to make room */
  /* +2 for EOB chars. */
    int number_to_move = (yy_n_chars)+2;
    char* dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
      YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
    char* source =
      &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

    while (source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf)
      *--dest = *--source;

    yy_cp += (int)(dest - source);
    yy_bp += (int)(dest - source);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
      (yy_n_chars) = (int)YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

    if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
      YY_FATAL_ERROR("flex scanner push-back overflow");
  }

  *--yy_cp = (char)c;

  /* %% [18.0] update yylineno here */

  (yytext_ptr) = yy_bp;
  (yy_hold_char) = *yy_cp;
  (yy_c_buf_p) = yy_cp;
}
/* %if-c-only */

/* %endif */
#endif

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput(void)
#else
static int input(void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
  int c;

  *(yy_c_buf_p) = (yy_hold_char);

  if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR)
  {
    /* yy_c_buf_p now points to the character we want to return.
     * If this occurs *before* the EOB characters, then it's a
     * valid NUL; if not, then we've hit the end of the buffer.
     */
    if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
      /* This was really a NUL. */
      *(yy_c_buf_p) = '\0';

    else
    { /* need more input */
      int offset = (int)((yy_c_buf_p)-(yytext_ptr));
      ++(yy_c_buf_p);

      switch (yy_get_next_buffer())
      {
      case EOB_ACT_LAST_MATCH:
        /* This happens because yy_g_n_b()
         * sees that we've accumulated a
         * token and flags that we need to
         * try matching the token before
         * proceeding.  But for input(),
         * there's no matching to consider.
         * So convert the EOB_ACT_LAST_MATCH
         * to EOB_ACT_END_OF_FILE.
         */

         /* Reset buffer status. */
        yyrestart(yyin);

        /*FALLTHROUGH*/

      case EOB_ACT_END_OF_FILE:
      {
        if (yywrap())
          return 0;

        if (!(yy_did_buffer_switch_on_eof))
          YY_NEW_FILE;
#ifdef __cplusplus
        return yyinput();
#else
        return input();
#endif
      }

      case EOB_ACT_CONTINUE_SCAN:
        (yy_c_buf_p) = (yytext_ptr)+offset;
        break;
      }
    }
  }

  c = *(unsigned char*)(yy_c_buf_p);	/* cast for 8-bit char's */
  *(yy_c_buf_p) = '\0';	/* preserve yytext */
  (yy_hold_char) = *++(yy_c_buf_p);

  /* %% [19.0] update BOL and yylineno */

  return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
 /* %if-c-only */
void yyrestart(FILE* input_file)
/* %endif */
/* %if-c++-only */
/* %endif */
{

  if (!YY_CURRENT_BUFFER) {
    yyensure_buffer_stack();
    YY_CURRENT_BUFFER_LVALUE =
      yy_create_buffer(yyin, YY_BUF_SIZE);
  }

  yy_init_buffer(YY_CURRENT_BUFFER, input_file);
  yy_load_buffer_state();
}

/* %if-c++-only */
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
 /* %if-c-only */
void yy_switch_to_buffer(YY_BUFFER_STATE  new_buffer)
/* %endif */
/* %if-c++-only */
/* %endif */
{

  /* TODO. We should be able to replace this entire function body
   * with
   *		yypop_buffer_state();
   *		yypush_buffer_state(new_buffer);
     */
  yyensure_buffer_stack();
  if (YY_CURRENT_BUFFER == new_buffer)
    return;

  if (YY_CURRENT_BUFFER)
  {
    /* Flush out information for old buffer. */
    *(yy_c_buf_p) = (yy_hold_char);
    YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  YY_CURRENT_BUFFER_LVALUE = new_buffer;
  yy_load_buffer_state();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  (yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
  (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
  /* %if-c-only */
  yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
  /* %endif */
  /* %if-c++-only */
  /* %endif */
  (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
 /* %if-c-only */
YY_BUFFER_STATE yy_create_buffer(FILE* file, int  size)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char*)yyalloc((yy_size_t)(b->yy_buf_size + 2));
  if (!b->yy_ch_buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer(b, file);

  return b;
}

/* %if-c++-only */
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
 /* %if-c-only */
void yy_delete_buffer(YY_BUFFER_STATE  b)
/* %endif */
/* %if-c++-only */
/* %endif */
{

  if (!b)
    return;

  if (b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
    YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

  if (b->yy_is_our_buffer)
    yyfree((void*)b->yy_ch_buf);

  yyfree((void*)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
 /* %if-c-only */
static void yy_init_buffer(YY_BUFFER_STATE  b, FILE* file)
/* %endif */
/* %if-c++-only */
/* %endif */

{
  int oerrno = errno;

  yy_flush_buffer(b);

  /* %if-c-only */
  b->yy_input_file = file;
  /* %endif */
  /* %if-c++-only */
  /* %endif */
  b->yy_fill_buffer = 1;

  /* If b is the current buffer, then yy_init_buffer was _probably_
   * called from yyrestart() or through yy_get_next_buffer.
   * In that case, we don't want to reset the lineno or column.
   */
  if (b != YY_CURRENT_BUFFER) {
    b->yy_bs_lineno = 1;
    b->yy_bs_column = 0;
  }

  /* %if-c-only */

  b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;

  /* %endif */
  /* %if-c++-only */
  /* %endif */
  errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
 /* %if-c-only */
void yy_flush_buffer(YY_BUFFER_STATE  b)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  if (!b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == YY_CURRENT_BUFFER)
    yy_load_buffer_state();
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
 /* %if-c-only */
void yypush_buffer_state(YY_BUFFER_STATE new_buffer)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  if (new_buffer == NULL)
    return;

  yyensure_buffer_stack();

  /* This block is copied from yy_switch_to_buffer. */
  if (YY_CURRENT_BUFFER)
  {
    /* Flush out information for old buffer. */
    *(yy_c_buf_p) = (yy_hold_char);
    YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
    YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
  }

  /* Only push if top exists. Otherwise, replace top. */
  if (YY_CURRENT_BUFFER)
    (yy_buffer_stack_top)++;
  YY_CURRENT_BUFFER_LVALUE = new_buffer;

  /* copied from yy_switch_to_buffer. */
  yy_load_buffer_state();
  (yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
 /* %if-c-only */
void yypop_buffer_state(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  if (!YY_CURRENT_BUFFER)
    return;

  yy_delete_buffer(YY_CURRENT_BUFFER);
  YY_CURRENT_BUFFER_LVALUE = NULL;
  if ((yy_buffer_stack_top) > 0)
    --(yy_buffer_stack_top);

  if (YY_CURRENT_BUFFER) {
    yy_load_buffer_state();
    (yy_did_buffer_switch_on_eof) = 1;
  }
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
 /* %if-c-only */
static void yyensure_buffer_stack(void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
  yy_size_t num_to_alloc;

  if (!(yy_buffer_stack)) {

    /* First allocation is just for 2 elements, since we don't know if this
     * scanner will even need a stack. We use 2 instead of 1 to avoid an
     * immediate realloc on the next call.
         */
    num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
    (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
    (num_to_alloc * sizeof(struct yy_buffer_state*)
    );
    if (!(yy_buffer_stack))
      YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

    memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

    (yy_buffer_stack_max) = num_to_alloc;
    (yy_buffer_stack_top) = 0;
    return;
  }

  if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {

    /* Increase the buffer to prepare for a possible push. */
    yy_size_t grow_size = 8 /* arbitrary grow size */;

    num_to_alloc = (yy_buffer_stack_max)+grow_size;
    (yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
    ((yy_buffer_stack),
      num_to_alloc * sizeof(struct yy_buffer_state*)
    );
    if (!(yy_buffer_stack))
      YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

    /* zero only the new slots.*/
    memset((yy_buffer_stack)+(yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
    (yy_buffer_stack_max) = num_to_alloc;
  }
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer(char* base, yy_size_t  size)
{
  YY_BUFFER_STATE b;

  if (size < 2 ||
    base[size - 2] != YY_END_OF_BUFFER_CHAR ||
    base[size - 1] != YY_END_OF_BUFFER_CHAR)
    /* They forgot to leave room for the EOB's. */
    return NULL;

  b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR("out of dynamic memory in yy_scan_buffer()");

  b->yy_buf_size = (int)(size - 2);	/* "- 2" to take care of EOB's */
  b->yy_buf_pos = b->yy_ch_buf = base;
  b->yy_is_our_buffer = 0;
  b->yy_input_file = NULL;
  b->yy_n_chars = b->yy_buf_size;
  b->yy_is_interactive = 0;
  b->yy_at_bol = 1;
  b->yy_fill_buffer = 0;
  b->yy_buffer_status = YY_BUFFER_NEW;

  yy_switch_to_buffer(b);

  return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string(const char* yystr)
{

  return yy_scan_bytes(yystr, (int)strlen(yystr));
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes(const char* yybytes, int  _yybytes_len)
{
  YY_BUFFER_STATE b;
  char* buf;
  yy_size_t n;
  int i;

  /* Get memory for full buffer, including space for trailing EOB's. */
  n = (yy_size_t)(_yybytes_len + 2);
  buf = (char*)yyalloc(n);
  if (!buf)
    YY_FATAL_ERROR("out of dynamic memory in yy_scan_bytes()");

  for (i = 0; i < _yybytes_len; ++i)
    buf[i] = yybytes[i];

  buf[_yybytes_len] = buf[_yybytes_len + 1] = YY_END_OF_BUFFER_CHAR;

  b = yy_scan_buffer(buf, n);
  if (!b)
    YY_FATAL_ERROR("bad buffer in yy_scan_bytes()");

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;

  return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yynoreturn yy_fatal_error(const char* msg)
{
  fprintf(stderr, "%s\n", msg);
  exit(YY_EXIT_FAILURE);
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 *
 */
int yyget_lineno(void)
{

  return yylineno;
}

/** Get the input stream.
 *
 */
FILE* yyget_in(void)
{
  return yyin;
}

/** Get the output stream.
 *
 */
FILE* yyget_out(void)
{
  return yyout;
}

/** Get the length of the current token.
 *
 */
int yyget_leng(void)
{
  return yyleng;
}

/** Get the current token.
 *
 */

char* yyget_text(void)
{
  return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param _line_number line number
 *
 */
void yyset_lineno(int  _line_number)
{

  yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in(FILE* _in_str)
{
  yyin = _in_str;
}

void yyset_out(FILE* _out_str)
{
  yyout = _out_str;
}

int yyget_debug(void)
{
  return yy_flex_debug;
}

void yyset_debug(int  _bdebug)
{
  yy_flex_debug = _bdebug;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals(void)
{
  /* Initialization is the same as for the non-reentrant scanner.
* This function is called from yylex_destroy(), so don't allocate here.
*/

  (yy_buffer_stack) = NULL;
  (yy_buffer_stack_top) = 0;
  (yy_buffer_stack_max) = 0;
  (yy_c_buf_p) = NULL;
  (yy_init) = 0;
  (yy_start) = 0;

  /* Defined in main.c */
#ifdef YY_STDINIT
  yyin = stdin;
  yyout = stdout;
#else
  yyin = NULL;
  yyout = NULL;
#endif

  /* For future reference: Set errno on error, since we are called by
   * yylex_init()
   */
  return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy(void)
{

  /* Pop the buffer stack, destroying each element. */
  while (YY_CURRENT_BUFFER) {
    yy_delete_buffer(YY_CURRENT_BUFFER);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    yypop_buffer_state();
  }

  /* Destroy the stack itself. */
  yyfree((yy_buffer_stack));
  (yy_buffer_stack) = NULL;

  /* Reset the globals. This is important in a non-reentrant scanner so the next time
   * yylex() is called, initialization will occur. */
  yy_init_globals();

  /* %if-reentrant */
  /* %endif */
  return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char* s1, const char* s2, int n)
{

  int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char* s)
{
  int n;
  for (n = 0; s[n]; ++n)
    ;

  return n;
}
#endif

void* yyalloc(yy_size_t  size)
{
  return malloc(size);
}

void* yyrealloc(void* ptr, yy_size_t  size)
{

  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return realloc(ptr, size);
}

void yyfree(void* ptr)
{
  free((char*)ptr);	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

